<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.cybnity</groupId>
		<artifactId>quality-control-applications</artifactId>
		<version>${revision}</version>
		<relativePath>..</relativePath>
	</parent>

	<groupId>org.cybnity.test</groupId>
	<artifactId>test-dimensions</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>
	<name>QUALITY CONTROL DIMENSION SYSTEMS</name>

	<modules>
		<!-- Shared utility libraries -->
		<module>commons</module>
		<!-- Implementation test component types -->
		<module>functional-acceptance-dimension</module>
		<module>technical-acceptance-dimension</module>
		<!-- Implementation test system types -->
		<module>test-systems</module>
	</modules>

	<!-- Common properties to all the sub-projects -->
	<properties>
		<!-- Version of CYBNITY Application tested -->
		<cybnity.software.revision>0.1.0</cybnity.software.revision>

		<!-- Docker platform supported for build of Docker images (e.g linux/amd64 on x86 CPU; or linux/arm64 on Mac M4 CPU) -->
		<docker.platforms>linux/amd64,linux/arm64,linux/arm64v8</docker.platforms>

		<!-- Test Plan project customization specific properties -->
		<testPlan-jar.mainClass>org.testng.TestNG</testPlan-jar.mainClass>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.cybnity.test</groupId>
				<artifactId>commons</artifactId>
				<version>${revision}</version>
				<scope>compile</scope>
			</dependency>
			<dependency>
				<groupId>org.cybnity.framework</groupId>
				<artifactId>support</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
			<dependency>
				<groupId>org.cybnity.framework</groupId>
				<artifactId>immutable</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
			<dependency>
				<groupId>org.cybnity.framework</groupId>
				<artifactId>domain</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
			<dependency>
				<groupId>org.cybnity.framework</groupId>
				<artifactId>vertx-common</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
			<dependency>
				<groupId>org.cybnity.infrastructure.integration.uis.adapters</groupId>
				<artifactId>api</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
			<dependency>
				<groupId>org.cybnity.infrastructure.integration.uis.adapters</groupId>
				<artifactId>redis-impl</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
			<dependency>
				<groupId>org.cybnity.infrastructure.registry.knr.adapters</groupId>
				<artifactId>api</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
			<dependency>
				<groupId>org.cybnity.infrastructure.registry.knr.adapters</groupId>
				<artifactId>janusgraph-impl</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
			<dependency>
				<groupId>org.cybnity.application.access-control.adapters</groupId>
				<artifactId>keycloak-admin-impl</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
			<dependency>
				<groupId>org.cybnity.features.technical.persistence</groupId>
				<artifactId>redis-store</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
			<dependency>
				<groupId>org.cybnity.features.technical.persistence</groupId>
				<artifactId>janusgraph-repository</artifactId>
				<version>${cybnity.software.revision}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
	    <!-- CUCUMBER tool for Functional test development in Behavior Driven Development (BDD) approach -->
		<!-- Available sub-dependencies documented at https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-bom/pom.xml -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <scope>compile</scope>
        </dependency>
		<dependency>
			<!-- Use TestNG to execute Cucumber scenarios -->
			<!-- TESTNG tool for test runtime packaging (support of IDE execution, Maven driven execution, java standalone execution) -->
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-testng</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<!-- LIbrary for use of rich AssertJ tool (rich set of assertions and truly helpful error messages, improves test code readability) in test plans. See https://assertj.github.io/doc/ for help -->
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<!-- Test code which depends on methods in java.lang.System (e.g; environment variables)
			It's a plugin/listener for the TestNG framework, which automatically injects System Stubs into TestNG tests
			-->
			<groupId>uk.org.webcompere</groupId>
			<artifactId>system-stubs-testng</artifactId>
			<scope>compile</scope>
		</dependency>
		<!--
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>testng-xml-formatter</artifactId>
			<scope>test</scope>
		</dependency>-->

		<!-- Dependencies usable for unit test phase of test plan utility projects under JUnit
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<scope>test</scope>
		</dependency> -->
		<dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite</artifactId>
            <scope>test</scope>
        </dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<configuration>
						<!-- Disable missing Javadoc warnings on Cucumber test classes for cause of BDD scenario descriptions are already formal and unambiguous -->
						<doclint>none</doclint>
						<failOnWarnings>false</failOnWarnings>
						<quiet>true</quiet>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-project-info-reports-plugin</artifactId>
				<version>2.6</version>
				<reportSets>
					<reportSet>
						<reports>
							<!-- select reports -->
							<report>index</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
		</plugins>
	</reporting>

	<profiles>
		<profile>
			<!-- Unique workstation on test plans execution -->
			<!-- ONLY TESTS THAT DOES NOT REQUIRE ANY EXTERNAL SYSTEM (e.g; none server component need) CAN BE PERFORMED UNDER THIS PROFILE -->
			<id>standalone</id>
			<activation>
				<activeByDefault>false</activeByDefault>
				<property>
					<!-- Activation based on defined UPPERCASE environment variable (e.g; TEST_ENV=standalone) -->
					<name>env.TEST_ENV</name>
					<value>standalone</value>
				</property>
			</activation>
			<properties>
				<!-- Configuration elements relative to specificity of the environment targeted by the test execution (EXECUTION CONTEXT) -->

			</properties>
		</profile>

		<profile>
			<!-- Shared development server between developers -->
			<!-- TESTS THAT REQUIRE OR NOT REQUIRE EXTERNAL SYSTEMS (e.g; Kubernetes server with deployed component running) CAN BE PERFORMED UNDER THIS PROFILE -->
			<id>dev-deploy-environment</id>
			<activation>
				<activeByDefault>false</activeByDefault>
				<property>
					<!-- Activation based on defined UPPERCASE environment variable (e.g; TEST_ENV=dev-deploy) -->
					<name>env.TEST_ENV</name>
					<value>dev-deploy</value>
				</property>
			</activation>
			<properties>
				<!-- Configuration elements relative to specificity of the environment targeted by the test execution (EXECUTION CONTEXT) -->
				<testplan.env.keycloak.server.url>https://dev-deploy.cybnity.tech</testplan.env.keycloak.server.url>
				<testplan.env.keycloak.realm.master.name>master</testplan.env.keycloak.realm.master.name>
				<testplan.env.keycloak.realm.master.username>admin</testplan.env.keycloak.realm.master.username>
				<testplan.env.keycloak.realm.master.password>admin</testplan.env.keycloak.realm.master.password>
				<testplan.env.keycloak.realm.master.clientid>admin-cli</testplan.env.keycloak.realm.master.clientid>
				<testplan.env.keycloak.realm.master.grant.type>password</testplan.env.keycloak.realm.master.grant.type>
				<testplan.env.keycloak.realm.default.frontend.url>https://dev-deploy.cybnity.tech/auth/</testplan.env.keycloak.realm.default.frontend.url>
				<testplan.env.keycloak.realm.default.security.header.xframe.options>SAMEORIGIN</testplan.env.keycloak.realm.default.security.header.xframe.options>
				<testplan.env.keycloak.realm.default.security.header.content.security.policy>"frame-src 'self'; frame-ancestors 'self'; object-src 'none';"</testplan.env.keycloak.realm.default.security.header.content.security.policy>
			</properties>
		</profile>

		<profile>
			<!-- Quality control server dedicated to test activities by CI/CD stage -->
			<id>qa-environment</id>
			<activation>
				<activeByDefault>false</activeByDefault>
				<property>
					<!-- Activation based on defined UPPERCASE environment variable (e.g; TEST_ENV=qa) -->
					<name>env.TEST_ENV</name>
					<value>qa</value>
				</property>
			</activation>
			<properties>
				<!-- Configuration elements relative to specificity of the environment targeted by the test execution (EXECUTION CONTEXT) -->

			</properties>
		</profile>

		<profile>
			<!-- Dedicated server context reserved for end-user manual test execution -->
			<id>uat-environment</id>
			<activation>
				<activeByDefault>false</activeByDefault>
				<property>
					<!-- Activation based on defined UPPERCASE environment variable (e.g; TEST_ENV=uat) -->
					<name>env.TEST_ENV</name>
					<value>uat</value>
				</property>
			</activation>
			<properties>
				<!-- Configuration elements relative to specificity of the environment targeted by the test execution (EXECUTION CONTEXT) -->
			</properties>
		</profile>

		<profile>
			<!-- Dedicated servers for performance verification tests execution -->
			<id>perf-environment</id>
			<activation>
				<activeByDefault>false</activeByDefault>
				<property>
					<!-- Activation based on defined UPPERCASE environment variable (e.g; TEST_ENV=perf) -->
					<name>env.TEST_ENV</name>
					<value>perf</value>
				</property>
			</activation>
			<properties>
				<!-- Configuration elements relative to specificity of the environment targeted by the test execution (EXECUTION CONTEXT) -->
			</properties>
		</profile>

		<profile>
			<!-- Test plans build phase (optionally including specific unit test relative to test data) -->
			<id>commit-stage</id>
			<activation>
				<activeByDefault>true</activeByDefault>
				<property>
					<!-- Activation based on defined UPPERCASE environment variable (e.g; STAGE=commit) -->
					<name>env.STAGE</name>
					<value>commit</value>
				</property>
			</activation>
			<properties>
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<!-- SCOPE OF TEST SCENARIO PRE-SELECTED FOR EXECUTION BY THIS PROFILE -->
						<!--<configuration>
							<excludes>
								<exclude>**/*Integration*.java</exclude>
								<exclude>**/*Manual*.java</exclude>
							</excludes>
						</configuration>-->
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<!-- Phase of technical quality validation of a software version -->
			<id>technical-quality-stage</id>
			<activation>
				<activeByDefault>false</activeByDefault>
				<property>
					<!-- Activation based on defined UPPERCASE environment variable (e.g; STAGE=tech-qa) -->
					<name>env.STAGE</name>
					<value>tech-qa</value>
				</property>
			</activation>
			<properties>
				<!-- Configuration elements relative to specificity of the stage (TEST GOAL) -->

				<!-- Performed CUCUMBER TEST THAT ARE TAGGED:  @technicalTest -->
				<!-- Including test plans:
						- Cybersecurity test plan
						- UI usability test plan
				-->
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<!-- SCOPE OF TEST SCENARIO PRE-SELECTED FOR EXECUTION BY THIS PROFILE -->
						<!--<configuration>
							<excludes>
								<exclude>**/*Integration*.java</exclude>
								<exclude>**/*Manual*.java</exclude>
							</excludes>
						</configuration>-->
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-dependency-plugin</artifactId>
						<executions>
							<execution>
								<id>resolve-dependency</id>
								<phase>validate</phase>
								<configuration>
									<silent>false</silent>
								</configuration>
								<goals>
									<!-- Try to resolve all test scope -->
									<goal>resolve</goal>
									<!-- Try to resolve plugins and optionally their dependencies -->
									<goal>resolve-plugins</goal>
								</goals>
							</execution>
							<execution>
								<id>analyze-dependencies</id>
								<phase>validate</phase>
								<goals>
									<!-- Determine missing or unused dependencies -->
									<goal>analyze-dep-mgt</goal>
									<goal>analyze-duplicate</goal>
								</goals>
							</execution>
							<execution>
								<id>report-tree</id>
								<phase>validate</phase>
								<configuration>
										<outputFile>mpp-official-version-pom-tree.txt</outputFile>
										<outputType>text</outputType>
										<appendOutput>false</appendOutput>
								</configuration>
								<goals>
									<!-- Show the dependency hierarchy of the project and dependencies versions managed by the parent pom.xml -->
									<goal>tree</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<!-- Phase of integration quality validation of a software version (e.g on an test environment) -->
			<id>integration-quality-stage</id>
			<activation>
				<property>
					<!-- Activation based on defined UPPERCASE environment variable (e.g; STAGE=int-qa) -->
					<name>env.STAGE</name>
					<value>int-qa</value>
				</property>
			</activation>
			<properties>
				<!-- Configuration elements relative to specificity of the stage (TEST GOAL) -->

				<!-- Performed CUCUMBER TEST THAT ARE TAGGED: @integrationTest -->
				<!-- Including test plans:
						- Domain Layer integration test plan
						- Application Layer integration test plan
						- UI Layer integration test plan
				-->
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<!-- SCOPE OF TEST SCENARIO PRE-SELECTED FOR EXECUTION BY THIS PROFILE -->
						<!--<configuration>
							<includes>
								<include>**/*Integration*.java</include>
							</includes>
							<excludes>
								<exclude>**/*Manual*.java</exclude>
							</excludes>
						</configuration>-->
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<!-- Step of software behavior validation by testers community (e.g regarding a software beta release) -->
			<id>functional-quality-stage</id>
			<activation>
				<property>
					<!-- Activation based on defined UPPERCASE environment variable (e.g; STAGE=func-qa) -->
					<name>env.STAGE</name>
					<value>func-qa</value>
				</property>
			</activation>
			<properties>
				<!-- Configuration elements relative to specificity of the stage (TEST GOAL) -->

				<!-- Performed CUCUMBER TEST THAT ARE TAGGED:  @successTest @exceptionTest @functionalTest -->
				<!-- Including test plans:
						- UI Modules capabilities test plan
						- Application Modules processes test plan
						- Feature Components test plan
				-->
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<!-- SCOPE OF TEST SCENARIO PRE-SELECTED FOR EXECUTION BY THIS PROFILE -->
						<!--<configuration>
							<includes>
								<include>**/*Manual*.java</include>
							</includes>
							<excludes>
								<exclude>**/*Integration*.java</exclude>
							</excludes>
						</configuration>-->
					</plugin>
				</plugins>
			</build>
		</profile>


		<profile>
			<!-- Step of software capacity, robustness, efficiency and scalability validation (e.g regarding a software beta release) -->
			<id>performance-quality-stage</id>
			<activation>
				<property>
					<!-- Activation based on defined UPPERCASE environment variable (e.g; STAGE=perf-qa) -->
					<name>env.STAGE</name>
					<value>perf-qa</value>
				</property>
			</activation>
			<properties>
				<!-- Configuration elements relative to specificity of the stage (TEST GOAL) -->

				<!-- Performed CUCUMBER TEST THAT ARE TAGGED:  @performanceTest -->
				<!-- Including test plans:
						- Performance test plan
				-->
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<!-- SCOPE OF TEST SCENARIO PRE-SELECTED FOR EXECUTION BY THIS PROFILE -->
						<!--<configuration>
							<includes>
								<include>**/*Perf*.java</include>
							</includes>
							<excludes>
								<exclude>**/*Integration*.java</exclude>
								<exclude>**/*Manual*.java</exclude>
							</excludes>
						</configuration>-->
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
