# Automated archiving of source codes repository to Bitbucket remote backup instance
name: Test Plan Assets Archiving
run-name: ARCHIVING - Source codes backup refresh
on:
  push:
    # execution when ...
    branches:
      - 'feature*'
      - 'main'
      - 'integration'
      - 'staging'
  delete:
    # execution when ...
    branches:
      - 'feature*'
      - 'main'
      - 'integration'
      - 'staging'

# The archiging stage workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror_repository_contents:
    name: Backup repository contents to Bitbucket
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Read reusable environment variables about current test plans project
        if: ${{ env.TAG_VERSION == '' }}
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Checkout source codes from branch
        id: checkout_step
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          ref: ${{ inputs.branch_name }}
          fetch-depth: 0 # <-- clone with complete history

      # See https://github.com/asaphdanchi/Mirror-and-synchronizing/blob/main/mirror-github-to-bitbucket.md
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Clone current GitHub repository
        run: |
          git clone --mirror https://github.com/cybnity/quality-control-plans.git github-repo

      - name: Set Git Author Email for Bitbucket
        run: |
          cd github-repo
          git config user.email "k7ityzq8ihv7qy1kecsh5agqtlwzp0@bots.bitbucket.org"

      - name: Push to Bitbucket Repository
        env:
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_API_REPO_TOKEN }}
        run: |
          cd github-repo
          git remote add quality-control-plans https://agnet:${{ secrets.BITBUCKET_API_REPO_TOKEN }}@bitbucket.org/agnet/REPOSITORY.git
          git push --mirror quality-control-plans

      #- name: "Push contents of $CI_REPOSITORY_NAME project to Bitbucket repository"
      #  uses: heussd/mirror-to-bitbucket-github-action@v2
      #  with:
      #      username: ${{ secrets.BITBUCKET_USERNAME }}
      #      spacename: ${{ secrets.BITBUCKET_WORKSPACE_NAME }}
      #      repository: $CI_REPOSITORY_NAME
      #      password: ${{ secrets.BITBUCKET_API_REPO_TOKEN }}
            ##password: ${{ secrets.BITBUCKET_APP_PASSWORD }}
