# Automated archiving of source codes repository to Bitbucket remote backup instance
name: Test Plan Assets Archiving
run-name: ARCHIVING - Source codes backup refresh
on:
  push:
    # execution when ...
    branches:
      - 'feature*'
      - 'main'
      - 'integration'
      - 'staging'
  delete:
    # execution when ...
    branches:
      - 'feature*'
      - 'main'
      - 'integration'
      - 'staging'

# The archiging stage workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror_repository_contents:
    name: Backup repository contents to Bitbucket
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Read reusable environment variables about current test plans project
        if: ${{ env.TAG_VERSION == '' }}
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Checkout source codes from branch
        id: checkout_step
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          ref: ${{ inputs.branch_name }}
          fetch-depth: 0 # <-- clone with complete history

      - name: Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
            target_repo_url: https://api.bitbucket.org/2.0/$CI_REPOSITORY_NAME
            ssh_private_key: ${{ secrets.BITBUCKET_API_REPO_TOKEN }}
            ssh_username: k7ityzq8ihv7qy1kecsh5agqtlwzp0@bots.bitbucket.org

      - name: "Push contents of $CI_REPOSITORY_NAME project to Bitbucket repository"
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
            username: ${{ secrets.BITBUCKET_USERNAME }}
            spacename: ${{ secrets.BITBUCKET_WORKSPACE_NAME }}
            repository: $CI_REPOSITORY_NAME
            password: ${{ secrets.BITBUCKET_API_REPO_TOKEN }}
            ##password: ${{ secrets.BITBUCKET_APP_PASSWORD }}
