# Automated archiving of source codes repository to Bitbucket remote backup instance
name: Test Plan Assets Archiving
run-name: ARCHIVING - Source codes backup update
on:
  push:
    # execution when ...
    branches:
      - 'feature*'
      - 'main'
      - 'integration'
      - 'staging'
  delete:
    # execution when ...
    branches:
      - 'feature*'
      - 'main'
      - 'integration'
      - 'staging'

# The archiging stage workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror_repository_contents:
    name: Backup repository mirror to AWS S3
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Read reusable environment variables about current test plans project
        if: ${{ env.TAG_VERSION == '' }}
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Checkout source codes from branch
        id: checkout_step
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          ref: ${{ inputs.branch_name }}
          fetch-depth: 0 # <-- clone with complete history

      # See https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#oidc-configuration-details
      # Get access to AWS resources using an IAM Role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: 'arn:aws:iam::974410204560:role/github-repository-archiver' # ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: 'eu-west-3' # ${{ secrets.AWS_S3_BUCKET_REGION }}
          output-credentials: true # reference the fetched credentials as outputs that allow to use the aws-session-token input in a situation where session tokens are fetched and passed to this action

      - name: Read caller identity connected over AWS Client
        run: |
          # AWS credentials read
          aws sts get-caller-identity for $CI_REPOSITORY_SLUG backup

      # See doc at https://github.com/fredydlemus/s3-backup
      - name: Compress repository to backup file and store into AWS S3 bucket
        uses: fredydlemus/s3-backup@v1
        with:
          target-bucket: 'amzn-s3-cybnity-github-mirror-bucket-974410204560-eu-west-3-an/quality-control-plans/' # Bucket name where to store repository mirrored files (backup)
          bucket-region: 'eu-west-3' # The WAS region where the S3 bucket is located
          role-arn: 'arn:aws:iam::974410204560:role/github-repository-archiver' # The ARN of the IAM role to assume for S3 access
          oidc-audience: 'sts.eu-west-3.amazonaws.com' # The audience value for the OIDC token
          backup-prefix: 'backup' # Prefix for the backup file name

